# -*- coding: utf-8 -*-
"""Email Spam Classifier | SMS Spam Classifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJ39VzZ4t69QPEiXPqY_IlPcuSFYCgug

# Email Spam Classifier | SMS Spam Classifier

Este projeto tem como objetivo aplicar técnicas de análise de dados e machine learning para resolver problemas reais, identificando padrões e tendências nos dados. Utilizando ferramentas como Python, Pandas, Scikit-learn e Power BI, o projeto envolve etapas de limpeza de dados, feature engineering e treinamento de modelos preditivos, além da apresentação de resultados visuais interativos.

Inspiração do projeto: https://www.youtube.com/watch?v=YncZ0WwxyzU&list=PLKnIA16_RmvY5eP91BGPa0vXUYmIdtfPQ&index=3


Data-set: https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset

# 1. Importando as bibliotecas que preciso:
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import files

"""# 2. Carregando o data-set:"""

# Instalar o kaggle
!pip install kaggle -q

# Colocar sua API Key do Kaggle:
files.upload()

# Criando uma pasta para colocar os arquivos:
!mkdir -p ~/.kaggle

# Copiando paa a pasta que foi criada
!cp kaggle.json ~/.kaggle

# Atribuindo uma conexão na pasta:
!chmod 600 ~/.kaggle/kaggle.json

# Listando os data sets disponíveis:
!kaggle datasets list

# Baixando o data-set:

!kaggle datasets download uciml/sms-spam-collection-dataset

# Desconectando o arquivo:
!unzip /content/sms-spam-collection-dataset.zip

# Carregando o data-set:

df = pd.read_csv('/content/spam.csv', encoding='ISO-8859-1')

df.head()

df.shape

"""#3. Data Cleaning:"""

df.info()

"""Vemos que v1 e v2 são as colunas importantes, o resto pode simplesmente ser apagado!"""

# Apagrando as últimas 3 colunas:

df.drop(columns = ['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace = True)

# Esse é o nosso data-set:
df.sample(5)

# Renomeando as colunas restantes:

df.rename(columns = {'v1':'target','v2':'text'}, inplace = True)
df.sample(5)

# Convertendo os valores categóricos em numéricos (LabelEncoder):

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

df['target'] = encoder.fit_transform(df['target'])
df.head(5)

# Valores faltando:

df.isnull().sum()

"""Vemos que não há valores faltando, então podemos seguir."""

# Conferindo se temos valores duplicados:

df.duplicated().sum()

"""Vemos que existem 403 valores duplicados, então vamos remover eles."""

# Removendo os valores duplicados:

df = df.drop_duplicates(keep = 'first')

df.duplicated().sum()

df.shape

"""#4. EDA (Exploratory Data Analysis - Análise Exploratória de Dados)"""

df['target'].value_counts()

"""Vemos que há uma certa difereça entre os conjuntos de dados em valores."""

import matplotlib.pyplot as plt

plt.pie(df['target'].value_counts(), labels = ['ham', 'spam'], autopct ='%0.2f')
plt.show()

"""Podemos ver que os dados estão desbalanceados.

# 5. Data Engineering:
"""

!pip install nltk

import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt')

# Número de caracteres usados em cada uma:
df['text'].apply(len)

df['num_characters'] = df['text'].apply(len)

df.head()

# Número de palavras:
import nltk
nltk.download('punkt_tab')
# Vamos tokenizar a variável texto, fazendo cada palavra um elemento:
df['num_words'] = df['text'].apply(lambda x: len(word_tokenize(x)))

df.head()

# número de sentenças:

df['num_sentences'] = df['text'].apply(lambda x:len (nltk.sent_tokenize(x)))

df.head()

df[['num_characters', 'num_words', 'num_sentences']].describe()

# Apenas os ham values:
df[df['target'] == 0][['num_characters', 'num_words', 'num_sentences']].describe()

# Apenas os spam values:
df[df['target'] == 1][['num_characters', 'num_words', 'num_sentences']].describe()

"""Vemos que no geral as métricas dos emails de spam são maiores que os que não são!"""

import seaborn as sns

plt.figure(figsize = (12, 6))
sns.histplot(df[df['target'] == 0]['num_characters'])
sns.histplot(df[df['target'] == 1]['num_characters'], color = 'red')

"""Podemos notar que as ham mensagens tem muitos menos caracteres que os spam!"""

# Fazendo o mesmo para as outras variáveis criadas:


plt.figure(figsize = (12, 6))
sns.histplot(df[df['target'] == 0]['num_words'])
sns.histplot(df[df['target'] == 1]['num_words'], color = 'red')

# Fazendo o mesmo para as outras variáveis criadas:


plt.figure(figsize = (12, 6))
sns.histplot(df[df['target'] == 0]['num_sentences'])
sns.histplot(df[df['target'] == 1]['num_sentences'], color = 'red')

# Vamos ver a correlação dos valores:

sns.pairplot(df, hue = 'target')

"""O gráfico de pares mostra a relação entre o número de caracteres, palavras e sentenças em mensagens, comparando-as com a variável target (0 ou 1). Há uma tendência clara de que mensagens mais longas (em termos de caracteres e palavras) sejam associadas ao target 1 (provavelmente spam). A relação linear entre o número de palavras e sentenças sugere que mensagens maiores têm mais sentenças."""

df.info()

df.drop(columns=['text']).corr()

sns.heatmap(df.drop(columns=['text']).corr(), annot=True)

"""# 6. Data Preprocessing:

- Letras minúsculas
- Tokenização
- Remoção de caracteres especiais
- Remoção de stop words e pontuação
- Stemming (redução para a raiz das palavras)
"""

df.head()

# Criando uma função para passar pelas frases e conferter tudo para letra minuscula:

def transform_text(text):
  text = text.lower()
  return text

transform_text('Hi how are You?')

"""Vemos que foi tudo para minúscula como gostariamos!"""

# Tokenização:

def transform_text(text):
  text = text.lower()
  text = nltk.word_tokenize(text)
  return text

transform_text('Hi how are You?')

"""Vemos que todas as palavras foram separadas!"""

# Removendo caracteres especiais:

def transform_text(text):
  text = text.lower()
  text = nltk.word_tokenize(text)

  y = []

  for i in text:
    if i.isalnum():
      y.append(i)

  return y

transform_text('Hi !o! are%%% You?.')

"""Vemos que ele não puxa os caracteres especiais!

Stop Words são palavras muito comuns em um idioma que, em geral, não agregam valor semântico relevante em tarefas de análise de texto, como modelos de Machine Learning ou Processamento de Linguagem Natural (NLP).
"""

# Removendo stop words:

from nltk.corpus import stopwords
nltk.download('stopwords')
stopwords.words('english')

# Vendo algumas em pt:
stopwords.words('portuguese')

import string
string.punctuation

# Removendo stop words e pontuações:

def transform_text(text):
  text = text.lower()
  text = nltk.word_tokenize(text)

  y = []

  for i in text:
    if i.isalnum():
      y.append(i)

  text = y[:]
  y.clear()
  for i in text:
    if i not in stopwords.words('english') and i not in string.punctuation:
      y.append(i)

  return y

transform_text("Hi !o! are%%% You? It's a beautiful day here in Brazil")

"""O Stemming é uma técnica de Processamento de Linguagem Natural (NLP) que consiste em reduzir palavras a sua raiz (stem), removendo prefixos e sufixos. Essa raiz geralmente não é uma palavra válida, mas representa a base semântica da palavra.

"""

#Stemming:

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
ps.stem('loving')

def transform_text(text):
  text = text.lower()
  text = nltk.word_tokenize(text)

  y = []

  for i in text:
    if i.isalnum():
      y.append(i)

  text = y[:]
  y.clear()
  for i in text:
    if i not in stopwords.words('english') and i not in string.punctuation:
      y.append(i)

  text = y[:]
  y.clear()

  for i in text:
    y.append(ps.stem(i))

  return " ".join(y)

transform_text('I loved the Youtube Lectures on Machine Learning... How about you?')

# Aplicando a função no nosso data-set:

df['transformed_text'] = df['text'].apply(transform_text)
df.head()

"""Vemos que estão aplicados todos os passos da função! Vamos ver agora as palavras mais recorrentes!"""

from wordcloud import WordCloud
wc = WordCloud(width = 500, height = 500, min_font_size = 10, background_color = 'white')

spam_wc = wc.generate(df[df['target'] == 1]['transformed_text'].str.cat(sep = " "))

plt.figure(figsize = (16,6))
plt.imshow(spam_wc)

"""O Word Cloud revela palavras comuns em mensagens de spam, destacando termos como "call" (ligar), "free" (grátis), "win" (ganhar) e "txt" (mensagem). Essas palavras indicam que mensagens de spam frequentemente oferecem prêmios falsos, promoções ou tentam induzir o usuário a entrar em contato por meio de ligações ou SMS. Termos como "stop" também são comuns, sugerindo instruções para cancelar o spam. O foco dessas mensagens é enganação e urgência, explorando ofertas e solicitações rápidas."""

ham_wc = wc.generate(df[df['target'] == 0]['transformed_text'].str.cat(sep = " "))

plt.figure(figsize = (16,6))
plt.imshow(ham_wc)

"""O Word Cloud de mensagens ham (não spam) mostra palavras comuns em comunicações cotidianas. Os termos mais frequentes incluem "go", "come", "got", "time", "call" e "want", indicando conversas relacionadas a planejamentos, encontros e comunicação pessoal. Palavras como "good", "love" e "ok" mostram um tom amigável e positivo. Diferente do spam, essas mensagens têm um tom informal e natural, focado em relacionamentos, interações pessoais e necessidades diárias."""

# Vamos converter os valores de txt para uma lista:

spam_corpus = []
for msg in df[df['target'] == 1]['transformed_text'].tolist():
  for word in msg.split():
      spam_corpus.append(word)

len(spam_corpus)

from collections import Counter
Counter(spam_corpus).most_common(30)

"""Vemos que corresponde com o gráfico de núvem das palavras visto acima!"""

from collections import Counter
sns.barplot(x=pd.DataFrame(Counter(spam_corpus).most_common(30))[0], y=pd.DataFrame(Counter(spam_corpus).most_common(30))[1])
plt.xticks(rotation='vertical')
plt.xlabel('')
plt.ylabel('')
plt.show()

"""O gráfico de barras mostra as 30 palavras mais frequentes em mensagens spam. As palavras "call", "free", "txt" e "claim" são as mais recorrentes, indicando que essas mensagens costumam conter ofertas gratuitas, solicitações de ligação ou prêmios. Termos como "win", "prize" e "urgent" sugerem tentativas de criar um senso de urgência ou engano. O padrão observado é comum em mensagens promocionais falsas, que buscam atrair atenção e enganar o destinatário.

"""

# Vamos converter os valores de txt para uma lista (agora para ham values):
ham_corpus = []
for msg in df[df['target'] == 0]['transformed_text'].tolist():
  for word in msg.split():
      ham_corpus.append(word)

len(ham_corpus)

from collections import Counter
sns.barplot(x=pd.DataFrame(Counter(ham_corpus).most_common(30))[0], y=pd.DataFrame(Counter(ham_corpus).most_common(30))[1])
plt.xticks(rotation='vertical')
plt.xlabel('')
plt.ylabel('')
plt.show()

"""O gráfico de barras mostra as 30 palavras mais frequentes em mensagens ham (não spam). A palavra "u" é a mais comum, destacando um tom informal e pessoal nas mensagens. Termos como "go", "get", "come", "call" e "time" sugerem planejamentos e interações sociais diárias. Além disso, palavras como "love" e "good" indicam um tom mais positivo e amigável, característico de conversas pessoais. Essas mensagens tendem a focar em relacionamentos e tarefas cotidianas, diferentemente de mensagens spam.

# 7. Model building:

Primeiramente vamos converter o nosso texto em matrizes numéricas para que o modelo possa entender:
"""

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

X = cv.fit_transform(df['transformed_text']).toarray()

X.shape

y = df['target'].values

y.shape

"""Dividindo em treino, teste:"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2)

"""Vamos testar diferentes modelos e investigar qual performa melhor:"""

from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score

"""Esses três modelos do Naive Bayes — GaussianNB, MultinomialNB e BernoulliNB — foram escolhidos porque são algoritmos eficientes para problemas de classificação de texto, como identificar se uma mensagem é spam ou ham."""

gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

# Primeiro modelo:
gnb.fit(X_train, y_train)
y_pred1 = gnb.predict(X_test)
print(accuracy_score(y_test, y_pred1))
print(confusion_matrix(y_test, y_pred1))
print(precision_score(y_test, y_pred1))

# Segundo modelo:
mnb.fit(X_train, y_train)
y_pred2 = mnb.predict(X_test)
print(accuracy_score(y_test, y_pred2))
print(confusion_matrix(y_test, y_pred2))
print(precision_score(y_test, y_pred2))

# Terceiro modelo:

bnb.fit(X_train, y_train)
y_pred3 = bnb.predict(X_test)
print(accuracy_score(y_test, y_pred3))
print(confusion_matrix(y_test, y_pred3))
print(precision_score(y_test, y_pred3))

"""Vamos tentar outra abordagem para melhorar essas métricas. O modelo Multinomial Naive Bayes (MNB) está sendo usado em conjunto com a técnica TF-IDF (Term Frequency - Inverse Document Frequency) para transformar o texto em números antes de ser passado para o classificador.


"""

from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
tfidf = TfidfVectorizer()

X = tfidf.fit_transform(df['transformed_text']).toarray()

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score

gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

gnb.fit(X_train,y_train)
y_pred1 = gnb.predict(X_test)
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(precision_score(y_test,y_pred1))

mnb.fit(X_train,y_train)
y_pred2 = mnb.predict(X_test)
print(accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))
print(precision_score(y_test,y_pred2))

bnb.fit(X_train,y_train)
y_pred3 = bnb.predict(X_test)
print(accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(precision_score(y_test,y_pred3))

"""Vimos que o melhor resultado foi atribuido ao uso do tfidf junto ao MNB! Vamos conduzir testes mais gerais para saber se iremos seguir assim!"""

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

svc = SVC(kernel='sigmoid', gamma=1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth=5)
lrc = LogisticRegression(solver='liblinear', penalty='l1')
rfc = RandomForestClassifier(n_estimators=50, random_state=2)
abc = AdaBoostClassifier(n_estimators=50, random_state=2)
bc = BaggingClassifier(n_estimators=50, random_state=2)
etc = ExtraTreesClassifier(n_estimators=50, random_state=2)
gbdt = GradientBoostingClassifier(n_estimators=50,random_state=2)
xgb = XGBClassifier(n_estimators=50,random_state=2)

clfs = {
    'SVC' : svc,
    'KN' : knc,
    'NB': mnb,
    'DT': dtc,
    'LR': lrc,
    'RF': rfc,
    'AdaBoost': abc,
    'BgC': bc,
    'ETC': etc,
    'GBDT':gbdt,
    'xgb':xgb
}

def train_classifier(clf,X_train,y_train,X_test,y_test):
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    precision = precision_score(y_test,y_pred)

    return accuracy,precision

train_classifier(svc,X_train,y_train,X_test,y_test)

accuracy_scores = []
precision_scores = []

for name,clf in clfs.items():

    current_accuracy,current_precision = train_classifier(clf, X_train,y_train,X_test,y_test)

    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)

    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

performance_df = pd.DataFrame({'Algorithm':clfs.keys(),'Accuracy':accuracy_scores,'Precision':precision_scores}).sort_values('Precision',ascending=False)
performance_df

performance_df1 = pd.melt(performance_df, id_vars = "Algorithm")
performance_df1

sns.catplot(x = 'Algorithm', y='value',
               hue = 'variable',data=performance_df1, kind='bar',height=5)
plt.ylim(0.5,1.0)
plt.xticks(rotation='vertical')
plt.show()

"""O gráfico compara os algoritmos de Machine Learning em termos de Accuracy (acurácia) e Precision (precisão para a classe positiva). O modelo K-Neighbors (KN) apresentou o melhor desempenho, com alta acurácia e precisão próximas de 1.0, sendo o mais indicado. O Naive Bayes (NB) também se destacou, com resultados consistentes em ambas as métricas. Modelos como Random Forest (RF), Extra Trees (ETC) e Support Vector Classifier (SVC) tiveram bom desempenho. Por outro lado, Decision Tree (DT) e AdaBoost apresentaram menor precisão, sendo menos eficazes para o problema.

# 8. Model improving:

Mudando os parâmetros de max_features do TfIdf:
"""

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, BaggingClassifier, ExtraTreesClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Data Preparation
cv = CountVectorizer()
tfidf = TfidfVectorizer(max_features=3000)
X = tfidf.fit_transform(df['transformed_text']).toarray()
y = df['target'].values

# Example Scaling (commented out for now)
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler()
# X = scaler.fit_transform(X)

# Appending num_character column to X
X = np.hstack((X, df['num_characters'].values.reshape(-1, 1)))

# Splitting the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model Definitions
clfs = {
    'SVC': SVC(kernel='sigmoid', gamma=1.0),
    'KN': KNeighborsClassifier(),
    'NB': MultinomialNB(),
    'DT': DecisionTreeClassifier(max_depth=5),
    'LR': LogisticRegression(solver='liblinear', penalty='l1'),
    'RF': RandomForestClassifier(n_estimators=50, random_state=2),
    'AdaBoost': AdaBoostClassifier(n_estimators=50, random_state=2),
    'BgC': BaggingClassifier(n_estimators=50, random_state=2),
    'ETC': ExtraTreesClassifier(n_estimators=50, random_state=2),
    'GBDT': GradientBoostingClassifier(n_estimators=50, random_state=2),
    'xgb': XGBClassifier(n_estimators=50, random_state=2)
}

# Train Classifier Function
def train_classifier(clf, X_train, y_train, X_test, y_test):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, zero_division=1)
    return accuracy, precision

# Placeholder for DataFrame
performance_df = pd.DataFrame({'Algorithm': list(clfs.keys())})

# Loop through each model and calculate metrics at different stages
for step, description in zip(['default', 'max_ft_3000', 'scaling', 'num_chars'], ["Default", "Max Features 3000", "Scaling Applied", "Num Characters Added"]):
    accuracy_scores = []
    precision_scores = []

    for name, clf in clfs.items():
        acc, prec = train_classifier(clf, X_train, y_train, X_test, y_test)
        accuracy_scores.append(acc)
        precision_scores.append(prec)

    performance_df[f'Accuracy_{step}'] = accuracy_scores
    performance_df[f'Precision_{step}'] = precision_scores

# Plotting the final performance
performance_df1 = pd.melt(performance_df, id_vars="Algorithm", var_name="Metric", value_name="Score")
sns.catplot(x='Algorithm', y='Score', hue='Metric', data=performance_df1, kind='bar', height=5)
plt.ylim(0.5, 1.0)
plt.xticks(rotation='vertical')
plt.title("Model Performance Comparison")
plt.show()

# Display the final DataFrame
print(performance_df)

"""O gráfico compara o desempenho de vários algoritmos de classificação usando diferentes métricas, como Accuracy e Precision. Os melhores modelos são Random Forest (RF), Extra Trees Classifier (ETC) e XGBoost (xgb), com accuracy acima de 97% e alta precisão. O Naive Bayes (NB) também apresenta boa performance, especialmente em precisão (98.85%). Algoritmos como Decision Tree (DT) e AdaBoost tiveram resultados razoáveis, mas com menor precisão. Modelos como K-Neighbors (KN) e Logistic Regression (LR) também performaram bem, mas com precisão um pouco menor. O SVC apresentou a maior precisão padrão, mas menor acurácia geral.

"""

# Cirando um modelo com os melhores desempenhos:

svc = SVC(kernel='sigmoid', gamma=1.0,probability=True)
mnb = MultinomialNB()
etc = ExtraTreesClassifier(n_estimators=50, random_state=2)

from sklearn.ensemble import VotingClassifier

voting = VotingClassifier(estimators=[('svm', svc), ('nb', mnb), ('et', etc)],voting='soft')

voting.fit(X_train,y_train)

y_pred = voting.predict(X_test)
print("Accuracy",accuracy_score(y_test,y_pred))
print("Precision",precision_score(y_test,y_pred))

# Aplicando stacking dos modelos:

estimators=[('svm', svc), ('nb', mnb), ('et', etc)]
final_estimator=RandomForestClassifier()

from sklearn.ensemble import StackingClassifier

clf = StackingClassifier(estimators=estimators, final_estimator=final_estimator)

clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print("Accuracy",accuracy_score(y_test,y_pred))
print("Precision",precision_score(y_test,y_pred))

import pickle
pickle.dump(tfidf,open('vectorizer.pkl','wb'))
pickle.dump(mnb,open('model.pkl','wb'))

"""# 9. Steamlit"""

!pip install streamlit -q

import streamlit as st

!wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501